language: ruby
rvm:
- 2.0.0
script:
- RAILS_ENV=test COVERAGE=true bundle exec rake --trace db:migrate spec cucumber
- RAILS_ENV=test COVERAGE=true bundle exec cucumber -p javascript
branches:
  only:
  - master
  - production
notifications:
  email:
    recipients:
    - gmacie@hotmail.com
    - jasnow@hotmail.com
    - jamesdabbs@gmail.com
    - chuachenh@grinnell.edu
    on_success: change
    on_failure: always
env:
  global:
    secure: VRuwF7UURbV590PUazKNyu4s2ePaEaadbkAmCp6mXrlOTumg9rau+L1S8iATIg1b4R3ogm3Mr72swx2nKkOWuYmhsnvpDUgRx+doAdHCNB38/jK26KT7jazf6XdzyazRxnISut8EaALOEL3hsFXK4jWrY+Me9jO69Jv7TzJK8SQ=
after_success:
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - git remote add heroku git@heroku.com:medlink-staging.git
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  - heroku keys:clear
  - yes | heroku keys:add
  - yes | git push heroku master
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
