language: ruby
bundler_args: --without development production
sudo: false
rvm:
- 2.3.1
script:
- RAILS_ENV=test COVERAGE=true bundle exec rake db:setup spec
env:
- s3_access_key_id=xxx s3_secret_access_key=xxx s3_bucket_name=xxx 
branches:
  only:
  - master
  - staging
  - production
notifications:
  email:
    recipients:
    - jamesdabbs@gmail.com
    on_success: change
    on_failure: always
addons:
  postgresql: "9.4"
